### PR TITLE
Add workflow and command line tests

### PR DESCRIPTION
**Pull request by geographika**
Currently testing on all branches but can revert to master following a review. 

This adds a GHA to build the client and run a few test examples from the command line. It then does a simple check to see that the file was created.

### CODE REVIEW

**Comment by KaiVolland** [comment]
@marcjansen as we talked about it. You want to have a look at this. Any thougths?

**Comment by jansule** [comment]
Do you think we can find a way to put the tests into a script so it is also possible to run them locally?

**Comment by geographika** [comment]
> Do you think we can find a way to put the tests into a script so it is also possible to run them locally?

@jansule - I've rewritten these tests as a script and added to package.json. 
It runs on Windows locally for me and on GHA, I'm not sure why the output goes to `stderr` rather than `stdout` though.

**Comment by jansule** [comment]
> > Do you think we can find a way to put the tests into a script so it is also possible to run them locally?
> 
> @jansule - I've rewritten these tests as a script and added to package.json. It runs on Windows locally for me and on GHA, I'm not sure why the output goes to `stderr` rather than `stdout` though.

That is weird, indeed. I just ran following code snippet from https://nodejs.org/api/child_process.html#child_processspawncommand-args-options and this seems to print to stdout:

```js
const { spawn } = require('node:child_process');
const ls = spawn('ls', ['-lh', '/usr']);

ls.stdout.on('data', (data) => {
  console.log(`stdout: ${data}`);
});

ls.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

ls.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
});
```

**Review by KaiVolland — APPROVED** [review]
IMHO this is good to go now.

**Comment by geographika** [comment]
Thanks for the review @KaiVolland. Once merged the tests will fail due to #344 but I plan to create a follow-up pull request with a fix for this and a test for multi-file output.

**Review by jansule — APPROVED** [review]
Very nice! Thanks @geographika

**Pull request merged**
