### PR TITLE
Make cli and standalone binaries build work

### LINKED ISSUE #398: ERR_REQUIRE_ESM
When I try to use GeoStyler with `npx geostyler-cli` I get the following message:

```
/Users/bart/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js:17
const geostyler_qgis_parser_1 = __importDefault(require("geostyler-qgis-parser"));
                                                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/bart/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js from /Users/bart/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js not supported.
Instead change the require of QGISStyleParser.js in /Users/bart/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/bart/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js:17:49) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v22.1.0
```

Wat are the supported Node versions?

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #398.

I failed to run the cli on MacOS with node20:
```
$ npx geostyler-cli -s sld -t mapbox --output out.json in.sld
Need to install the following packages:
geostyler-cli@4.0.0
Ok to proceed? (y) y

/Users/ahocevar/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js:17
const geostyler_qgis_parser_1 = __importDefault(require("geostyler-qgis-parser"));
                                                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ahocevar/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js from /Users/ahocevar/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js not supported.
Instead change the require of QGISStyleParser.js in /Users/ahocevar/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/ahocevar/.npm/_npx/d2b78a7bedb6eda9/node_modules/geostyler-cli/dist/src/index.js:17:49) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.17.0
```
Also, building the binaries spits out hundreds of babel and bytecode warnings. It seems pkg does not pick up the `bin` setting from package.json properly

This pull request fixes both problems:
* A single `geostyler.js` file without dependencies is a good entry point for both pkg and running the cli bin
* Inlining the pkg config in the pkg cli call and removing the config from package.json fixes the pkg build

The single `geostyler.js` cli bin has another advantage: all dependencies are now `devDependencies`, so `npx geostyler-cli` will install much faster - without the need to download dependency packages.

### CODE REVIEW

**Comment by KaiVolland** [comment]
Would be nice if you could check if this also works with the latests versions of the geostyler packages:

```
    "geostyler-lyrx-parser": "^1.0.1",
    "geostyler-mapbox-parser": "^6.0.0",
    "geostyler-mapfile-parser": "^4.0.1",
    "geostyler-qgis-parser": "^3.0.0",
    "geostyler-sld-parser": "^6.1.2",
    "geostyler-style": "^9.1.0",
```

**Comment by ahocevar** [comment]
@KaiVolland It does. Pushed a commit which updates those dependencies to the versions you posted above.

**Comment by ahocevar** [comment]
@KaiVolland Any chance you could publish a new version of the CLI with the recent fixes? Thanks in advance.

**Comment by KaiVolland** [comment]
@ahocevar sry that somehow got lost. :angel: :slightly_smiling_face:

**Pull request merged**
